### ISSUE TITLE
Module has no default export and Parameter 'err' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by andreia-oca** [Genez-io/genezio#153]
I am creating a TypeScript todo app from scratch and I am receiving the following errors when running `genezio local`.
I am pretty sure that I have all the packages installed with `npm install` and they are added as dependencies in `package.json`.

``` 
Syntax error:
[tsl] ERROR in /home/andreia/genezio-examples/typescript/todo-list/server/user.ts(2,8)
      TS1192: Module '"/home/andreia/genezio-examples/typescript/todo-list/server/node_modules/@types/jsonwebtoken/index"' has no default export.
 Syntax error:
[tsl] ERROR in /home/andreia/genezio-examples/typescript/todo-list/server/helper.ts(2,8)
      TS1192: Module '"/home/andreia/genezio-examples/typescript/todo-list/server/node_modules/@types/bcryptjs/index"' has no default export.
```

Can you help me to figure it out?

**Comment by radu1122** [comment]
Hi,

Can you provide me your `tsconfig` file?

Thank you

**Comment by andreia-oca** [comment]
Sure, this is the `tsconfig.json` on the server/backend side:

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "lib": [
            "es6",
            "dom"
        ],
        "outDir": "build",
        "rootDir": ".",
        "strict": true,
        "noImplicitAny": true,
        "resolveJsonModule": true,
        "allowJs": true,
        "types": [
            "node"
        ]
    },
    "include": [
        "**/*"
    ]
}
```

**Comment by radu1122** [comment]
Here is the problem.

You should add the following code in your `compilerOptions` in `tsconfig.json`:
`  "allowSyntheticDefaultImports": true,
    "esModuleInterop": true`

Let me know if I can provide further assistance with other topics.

**Comment by andreia-oca** [comment]
It works now, thanks a lot!
