### ISSUE TITLE
[Bug]: .genezioignore doesn't behave correctly with relative paths

### ISSUE THREAD

**Issue by laurci** [Genez-io/genezio#616]
### Describe your bug

For a simple empty project that looks like this:
```
temp
├── .genezioignore
├── genezio.yaml
├── test
│   ├── 1
│   ├── 2
│   ├── 3
│   ├── 4
│   └── 5
└── test.js
```
And the following `.genezioignore` file:
```
test/
```
I would expect `genezio deploy` to include only the following 3 files:
```
.genezioignore
genezio.yaml
test.js
```
Instead, it includes the following 9 files:
```
.genezioignore
genezio.yaml
test
test.js
1
2
3
4
```

### Small improvement

Related to the same problem, another inconvenience is that I can't negate matches. For example, I would assume that `!test/1` would include only `test/1` and exclude everything else. But this is not mentioned in the documentation as working, so it's not a bug.

### genezio version

0.6.4

**Comment by andreia-oca** [comment]
Hi,
Thanks a lot for your contribution! I just reviewed and tested it and it works like a charm 🚀

Would you also like to create a PR to update the documentation to reflect your improvement?

You can add changes in this markdown file [1]. Feel free to add me as a reviewer.
Once the documentation PR is merged it will automatically be updated in our documentation.

[1] https://github.com/Genez-io/genezio-documentation/blob/main/project-structure/.genezioignore.md
